#!/usr/bin/env python3
"""HTML Report Generator"""
import datetime, socket, json

def generate_report(data, output_path):
    sev_colors = {"CRITICAL":"#dc2626","HIGH":"#ea580c","MEDIUM":"#ca8a04","LOW":"#2563eb","INFO":"#16a34a"}
    findings_html = ""
    for f in data["findings"]:
        color = sev_colors.get(f["severity"], "#6b7280")
        findings_html += f"""
        <tr>
          <td><span style="background:{color};color:#fff;padding:2px 8px;border-radius:4px;font-size:12px;font-weight:bold">{f['severity']}</span></td>
          <td>{f['module']}</td>
          <td>{f['finding']}</td>
          <td>{f.get('recommendation','')}</td>
          <td>{f.get('nist_control','')}</td>
        </tr>"""

    score = data["risk_score"]
    score_color = "#16a34a" if score >= 85 else "#ca8a04" if score >= 60 else "#dc2626"
    html = f"""<!DOCTYPE html>
<html><head><meta charset="utf-8"><title>Security Audit Report</title>
<style>
  body{{font-family:Arial,sans-serif;max-width:1100px;margin:0 auto;padding:24px;background:#f9fafb}}
  h1{{color:#1e3a5f}}h2{{color:#374151;border-bottom:2px solid #e5e7eb;padding-bottom:8px}}
  table{{width:100%;border-collapse:collapse;margin-top:16px}}
  th{{background:#1e3a5f;color:#fff;padding:10px;text-align:left;font-size:13px}}
  td{{padding:8px 10px;border-bottom:1px solid #e5e7eb;font-size:13px;vertical-align:top}}
  tr:hover{{background:#f3f4f6}}
  .score{{font-size:48px;font-weight:bold;color:{score_color}}}
  .meta{{background:#fff;padding:16px;border-radius:8px;border:1px solid #e5e7eb;margin-bottom:24px}}
</style></head><body>
<h1>🔒 Security Audit Report</h1>
<div class="meta">
  <strong>Host:</strong> {data['host']} &nbsp;|&nbsp;
  <strong>Date:</strong> {data['timestamp'][:19]} &nbsp;|&nbsp;
  <strong>Total Findings:</strong> {len(data['findings'])}
  <br><br>
  <span class="score">{score}/100</span> &nbsp; Risk Score
</div>
<h2>Findings</h2>
<table><tr><th>Severity</th><th>Module</th><th>Finding</th><th>Recommendation</th><th>NIST Control</th></tr>
{findings_html}
</table>
<p style="color:#9ca3af;font-size:12px;margin-top:32px">
Generated by Security Audit Toolkit — Forsman Technology &amp; Consulting |
Aligned with NIST SP 800-53 &amp; CIS Benchmarks
</p></body></html>"""
    with open(output_path, "w") as f:
        f.write(html)
